import {Link} from "react-router-dom";

import "./Cookie.css";

import Button from "../../components/Button/Button";
import CookieCard from "./components/CookieCard/CookieCard";

import logoBlack from "../../assets/img/logo_black.svg";
import One from "../../assets/img/icons/1_Point.svg";
import Two from "../../assets/img/icons/2_Point.svg";
import Three from "../../assets/img/icons/3_Point.svg";
import Four from "../../assets/img/icons/4_Point.svg";
import Five from "../../assets/img/icons/5_Point.svg";
import Six from "../../assets/img/icons/6_Point.svg";
import Seven from "../../assets/img/icons/7_Point.svg";
import Eight from "../../assets/img/icons/8_Point.svg";
import Nine from "../../assets/img/icons/9_Point.svg";
import Ten from "../../assets/img/icons/10_Point.svg";
import Eleven from "../../assets/img/icons/11_Point.svg";
import Twelve from "../../assets/img/icons/12_Point.svg";
import Thirteen from "../../assets/img/icons/13_Point.svg";
import Header from "../../Layout/Header/Header";

const renderOne = () => {
    return (
        <div className="long">
            <p className="cookie-paragraph">To help explain things as clearly as possible in this Cookie Policy, every
                time any of these terms are referenced, are strictly defined as:</p>
            <ul className="cookie-list">
                <li><span><b>Cookie:</b> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</span>
                </li>
                <li><b>Company:</b> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to ITDRS that
                    is responsible for your information under this Cookie Policy.
                </li>
                <li><b>Device:</b> any internet connected device such as a phone, tablet, computer or any other device
                    that can be used to visit ITDRS and use the services.
                </li>
                <li><b>Personal Data:</b> any information that directly, indirectly, or in connection with other
                    information — including a personal identification number — allows for the identification or
                    identifiability of a natural person.
                </li>
                <li><b>Service:</b> refers to the service provided by ITDRS as described in the relative terms (if
                    available) and on this platform.
                </li>
                <li><b>Third-party service:</b> refers to advertisers, contest sponsors, promotional and marketing
                    partners, and others who provide our content or whose products or services we think may interest
                    you.
                </li>
                <li><b>Website:</b> IT and Design RS d.o.o. site, which can be accessed via this URL: https://itdrs.tech.</li>
                <li><b>You:</b> a person or entity that is registered with ITDRS to use the Services.</li>
            </ul>
        </div>
    )
}

const renderFour = () => {
    return (
        <div className="long">
            <p className="cookie-paragraph">
                We use first party and/or third party cookies on our platform for various purposes such as:
            </p>
            <ul className="cookie-list">
                <li>To facilitate the operation and functionality of our platform;</li>
                <li>To improve your experience of our platform and make navigating around them quicker and easier;</li>
                <li>To allow us to make a bespoke user experience for you and for us to understand what is useful or of
                    interest to you;
                </li>
                <li>To analyze how our platform is used and how best we can customize it;</li>
                <li>To identify future prospects and personalize marketing and sales interactions with it;</li>
                <li>To facilitate the tailoring of online advertising to your interests.</li>
            </ul>
        </div>
    )
}

const renderFive = () => {
    return (
        <div className="long">
            <p className="cookie-paragraph">Cookies can either be session cookies or persistent cookies. A session
                cookie expires automatically when you close your browser. A persistent cookie will remain until it
                expires or you delete your cookies. Expiration dates are set in the cookies themselves; some may expire
                after a few minutes while others may expire after multiple years. Cookies placed by the website you’re
                visiting are called “first party cookies”.</p>
            <p className="cookie-paragraph">Strictly Necessary cookies are necessary for our platform to function and
                cannot be switched off in our systems. They are essential in order to enable you to navigate around the
                platform and use its features. If you remove or disable these cookies, we cannot guarantee that you will
                be able to use our platform.</p>
            <p className="cookie-paragraph">We use the following types of cookies in our platform:</p>
        </div>
    )
}

const renderEight = () => {
    return (
        <div className="long">
            <p className="cookie-paragraph">These cookies collect information that is used to help us understand how our
                platform is being used or how effective our marketing campaigns are, or to help us customize our
                platform for you.</p>
            <p>We use cookies served by Google Analytics to collect limited data directly from end-user browsers to
                enable us to better understand your use of our platform. Further information on how Google collects and
                uses this data can be found at: https://www.google.com/
                <wbr/>
                policies/
                <wbr/>
                privacy/
                <wbr/>
                partners/. You can opt-out of all Google supported analytics on our Websites by visiting:
                https://tools.google.com/
                <wbr/>
                dlpage/
                <wbr/>
                gaoptout.
            </p>
        </div>
    )
}

const renderTen = () => {
    return (
        <>
            <p className="cookie-paragraph">Most browsers allow you to control cookies through their \'settings\'
                preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall
                user experience, since it will no longer be personalized to you. It may also stop you from saving
                customized settings like login information. Browser manufacturers provide help pages relating to cookie
                management in their products.</p>
            <p>Browser manufacturers provide help pages relating to cookie management in their products.</p>
        </>
    )
}

const renderEleven = () => {
    return (
        <div className="long">
            Wherever you\'re located you may also set your browser to block cookies and similar technologies, but this
            action may block our essential cookies and prevent our website from functioning properly, and you may not be
            able to fully utilize all of its features and services. You should also be aware that you may also lose some
            saved information (e.g. saved login details, site preferences) if you block cookies on your browser.
            Different browsers make different controls available to you. Disabling a cookie or category of cookie does
            not delete the cookie from your browser, you will need to do this yourself from within your browser, you
            should visit your browser\'s help menu for more information.
        </div>
    )
}

const cardsInfo = [
    {
        area: 'one',
        icon: One,
        title: 'Definitions And Key Terms',
        description: renderOne()
    },
    {
        area: 'two',
        icon: Two,
        title: 'Introduction',
        description: 'This Cookie Policy explains how IT and Design RS d.o.o. and its affiliates (collectively "ITDRS", "we", "us", and "ours"), use cookies and similar technologies to recognize you when you visit our platform, including without limitation https://itdrs.tech and any related URLs, mobile or localized versions and related domains / sub-domains ("Websites"). It explains what these technologies are and why we use them, as well as the choices for how to control them.'
    },
    {
        area: 'three',
        icon: Three,
        title: 'What Is \n A Cookie?',
        description: 'A cookie is a small text file that is stored on your computer or other internet connected device in order to identify your browser, provide analytics, remember information about you such as your language preference or login information. They\'re completely safe and can\'t be used to run programs or deliver viruses to your device.'
    },
    {
        area: 'four',
        icon: Four,
        title: 'Why Do We Use Cookies?',
        description: renderFour()
    },
    {
        area: 'five',
        icon: Five,
        title: 'What Type Of Cookies \n Does ITDRS Use?',
        description: renderFive()
    },
    {
        area: 'six',
        icon: Six,
        title: 'Essential Cookies',
        description: 'We use essential cookies to make our platform work. These cookies are strictly necessary to enable core functionality such as security, network management, your cookie preferences and accessibility. Without them you wouldn\'t be able to use basic services. You may disable these by changing your browser settings, but this may affect how the Websites function.'
    },
    {
        area: 'seven',
        icon: Seven,
        title: 'Performance \n And Functionality Cookies',
        description: 'These cookies are used to enhance the performance and functionality of our platform but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the platform as we would not be able to remember that you had logged in previously.'
    },
    {
        area: 'eight',
        icon: Eight,
        title: 'Analytics \n And Customization Cookies',
        description: renderEight()
    },
    {
        area: 'nine',
        icon: Nine,
        title: 'Third Party Cookies',
        description: 'Some cookies that have been set on our platform are not set on a first party basis by ITDRS. The Websites can be embedded with content from third parties to serve advertising. These third party service providers may set their own cookies on your web browser. Third party service providers control many of the performance and functionality, advertising, marketing and analytics cookies described above. We do not control the use of these third party cookies as cookies can only be accessed by the third party that originally set them.'
    },
    {
        area: 'ten',
        icon: Ten,
        title: 'How You Can Manage Cookies?',
        description: renderTen()
    },
    {
        area: 'eleven',
        icon: Eleven,
        title: 'Blocking And Disabling \n Cookies And Similar \n Technologies',
        description: renderEleven()
    },
    {
        area: 'twelve',
        icon: Twelve,
        title: 'Changes To Our \n Cookie Policy',
        description: 'We may change our Service and policies, and we may need to make changes to this Cookie Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Cookie Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Cookie Policy. If you do not want to agree to this or any updated Cookie Policy, you can delete your account.'
    },
    {
        area: 'thirteen',
        icon: Thirteen,
        title: 'Your Consent',
        description: 'By using our platform, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to its terms.'
    }
]

const Cookie = () => {
    return (
        <div className="content-page-wrapper">
            <div className="content">
                {/*<header className="header">*/}
                {/*    <Link to="/">*/}
                {/*        <img className="logo" src={logoBlack} alt="IT & Design"/>*/}
                {/*    </Link>*/}
                {/*    <Link to="/#contact"><Button/></Link>*/}
                {/*</header>*/}
                <Header inverseColors={true}/>
                <h1 className="cookie-title">Cookie Policy</h1>
                <div className="cookie-badge">Updated at 2023-01-21</div>
            </div>

            <div className="cookie-cards cookie-content">
                {cardsInfo.map(({area, icon, title, description}, idx) => (
                    <CookieCard
                        key={idx}
                        area={area}
                        icon={icon}
                        title={title}
                        width={650}
                    >
                        <div className="cookie-description">
                            {description}
                        </div>
                    </CookieCard>
                ))}
            </div>
        </div>
    )
}

export default Cookie;
